[package]
name = "distilled_derive"
version = "0.1.0"
edition = "2024"

[lib]
name = "distilled_derive"
path = "src/lib.rs"
proc-macro = true

[dependencies]
darling = "0.20.11"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
